// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGK8g3yo-q8ldJoLh2jw_iyMXqDVWcRoQ',
    appId: '1:617691353642:web:3c5ae14664da1bebf8a953',
    messagingSenderId: '617691353642',
    projectId: 'flutter-project-b7b9b',
    authDomain: 'flutter-project-b7b9b.firebaseapp.com',
    storageBucket: 'flutter-project-b7b9b.appspot.com',
    measurementId: 'G-F3K56M82ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGVLEQps_87CHH-ZdTcVAOe_PVsxfKlpw',
    appId: '1:617691353642:android:785952deeb610d4ef8a953',
    messagingSenderId: '617691353642',
    projectId: 'flutter-project-b7b9b',
    storageBucket: 'flutter-project-b7b9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-Tz5bwT99cjh2eADQgPEGKhT3OrJncw',
    appId: '1:617691353642:ios:9662661905b203d5f8a953',
    messagingSenderId: '617691353642',
    projectId: 'flutter-project-b7b9b',
    storageBucket: 'flutter-project-b7b9b.appspot.com',
    iosClientId: '617691353642-1doff49v8tu5kkdtfov8mfbuv39hh4cq.apps.googleusercontent.com',
    iosBundleId: 'com.flutterProject.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-Tz5bwT99cjh2eADQgPEGKhT3OrJncw',
    appId: '1:617691353642:ios:ebf7d97ebdb9c002f8a953',
    messagingSenderId: '617691353642',
    projectId: 'flutter-project-b7b9b',
    storageBucket: 'flutter-project-b7b9b.appspot.com',
    iosClientId: '617691353642-fmkd5093v09526uv76vt1jhe1a5h12ua.apps.googleusercontent.com',
    iosBundleId: 'com.flutterProject.mynotes.RunnerTests',
  );
}
